server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EC-service
          uri: lb://EC-service
          predicates:
            - Path=/EC/**
          filters:
            - RewritePath=/EC/(?<path>.*), /$\{path}
        - id: recipe-service
          uri: lb://recipe-service
          predicates:
            - Path=/recipe/**
          filters:
            - RewritePath=/recipe/(?<path>.*), /$\{path}
        - id: shared-service
          uri: lb://shared-service
          predicates:
            - Path=/shared/**
          filters:
            - RewritePath=/shared/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: EC
        url: /v3/api-docs/EC
      - name: recipe
        url: /v3/api-docs/recipe
      - name: shared
        url: /v3/api-docs/shared