server:
  port: 7000

#axon:
#  serializer:
#    general: xstream
#  axonserver:
#    servers: 127.0.0.1:8124

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: equipment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: example
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    database: postgresql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"