spring:
  application:
    name: shared-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8088}"
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: equipment
#    password: equipment
#  jpa:
#    hibernate:
#      ddl-auto: create
#    generate-ddl: false
#    show-sql: true
#    database: oracle
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#logging:
#  level:
#    org:
#      hibernate: info